log_level = "info"
#network = "shielded-expedition"
network = "luminara"

[database]
host = "localhost"
user = "postgres"
password = "wow"
dbname = "blockchain"
# Optional field to configure a timeout if database connection 
# fails.
connection_timeout = 20


[server]
serve_at = "0.0.0.0"
port = 30303

[indexer]
tendermint_addr = "http://IP:26657"

[jaeger]
enable = true
host = "localhost"
port = 6831

[prometheus]
host = "0.0.0.0"
port = 9000
